# Project-wide Gradle settings.
# Increase JVM heap size to 4GB to support Compose compiler and Kotlin daemon smoothly
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
